# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DurbinLevinsonEigen <- function(X, Y, acf, calcMode = 1L) {
    .Call('LMN_DurbinLevinson_Eigen', PACKAGE = 'LMN', X, Y, acf, calcMode)
}

DurbinLevinsonBase <- function(X, Y, acf, calcMode = 1L) {
    .Call('LMN_DurbinLevinson_Base', PACKAGE = 'LMN', X, Y, acf, calcMode)
}

